version: 2
updates:
  - package-ecosystem: "npm"
    directory: "website"
    schedule:
      interval: "monthly"
    # Disable all pull requests for docs site dependencies
    open-pull-requests-limit: 0
